### ISSUE TITLE
How to write unit testing with VIPERBuilder

### ISSUE THREAD

**Issue by deda9** [etsy/VIPERBuilder#5]
I used to use VIPER with `Presenter` & `Interactor` & `Router` variables in the UIViewController but I after awhile I found `VIPERBuilder` saves the time and make the code more readble, but I have a problem when write unit testing for VIPER component with VIPERBuilder, because the viperBuilder in the next code depends on the concrete implementation not the abstract, but in the old way the variable was protocols which you can mock easily. 

 ```swift
lazy var viperBuilder:
        VIPERBuilder<DemoInteractor, DemoPresenter, DemoRouter> = {
        return VIPERBuilder(controller: self)
    }()
```

I already made some work around to write the unit testing but this is not straight forward.

**Comment by macdoum1** [comment]
Hi @deda9 thanks for the question!

Typically we test the interactor, presenter and router in isolation, however for the cases we want to test whatever (usually a `UIViewController` subclass) owns the `VIPERBuilder` instance we use dependency injection via a setter.

For example:

```
let controller = DemoController()

// We want to mock some behavior of the VIPER flow, so we are swapping in a
// VIPERBuilder with a mocked presenter
let presenter = TestPresenter()
let viperBuilder: VIPERBuilder<DemoInteractor, DemoPresenter, DemoRouter> =
    VIPERBuilder(controller: vc,
                 interactor: vc.viperBuilder.interactor,
                 presenter: presenter,
                 router: vc.viperBuilder.router)
vc.viperBuilder = viperBuilder
    
// .. Perform some action on controller and assert


class TestPresenter: DemoPresenter {
// .. mocked behavior
}

```

I think there might be some room for improvement here, whether it be protocols/associatedtypes to make testing a bit easier.

**Comment by deda9** [comment]
@macdoum1 Thank you for your reply.

Usually I test the interactor, presenter and router in isolation, but when I need to test how the VC will interact with them, so I couldn't to mock and inject them into VC, cause VC expected to get concrete implementation.

whats the second `DemoInteractor` in `VIPERBuilder<DemoInteractor, DemoInteractor, DemoRouter>`  Do you mean `TestPresenter` and if so whats the sub class for this presenter cause VC expected to get DemoPresenter?

**Comment by macdoum1** [comment]
Hi again!

Sorry updated my snippet with t

So since you'll be injecting `VIPERBuilder<DemoInteractor, DemoInteractor, DemoRouter>` into your view controller you'll need your presenter to be of type

**Comment by macdoum1** [comment]
Hi again!

Sorry, fixed the type and added a bit more context. Since the `VIPERBuilder` instance you need to inject has the `<DemoInteractor, DemoPresenter, DemoRouter>` specification, you'll need the presenter to be of type `DemoPresenter`. One possible way to achieve this is to subclass `DemoPresenter` and mock out its behavior
